services:
  pedidos-service:
    build:
      context: ./pedidos-service/DeliveryHub.Pedidos.Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    networks:
      - deliveryhub-net

  entregas-service:
    build:
      context: ./entregas-service/DeliveryHub.Entregas.Api
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    networks:
      - deliveryhub-net

  entregadores-service:
    build:
      context: ./entregadores-service/DeliveryHub.Entregadores.Api
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - deliveryhub-net

  auth-service:
    build:
      context: ./auth-service/DeliveryHub.Auth.Api
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - deliveryhub-net

  gateway:
    build:
      context: ./gateway/DeliveryHub.Gateway
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      pedidos-service:
        condition: service_started
      entregas-service:
        condition: service_started
      entregadores-service:
        condition: service_started
      auth-service:
        condition: service_started
    networks:
      - deliveryhub-net

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - deliveryhub-net

  postgres:
    image: postgres:15
    container_name: deliveryhub-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pedidosdb
    ports:
      - "5432:5432"
    networks:
      - deliveryhub-net
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  deliveryhub-net:

volumes:
  pgdata:
